spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/hackerthon?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  config:
    import: optional:file:.env[.properties]
jwt:
  header: Authorization
  secret: pU4rnmUp6gk0KpqvA3jJfdBZnwr1APWOfiTDDJByZIz37y1vUIfa4oTMM8XK3J6dKUpxKp7GzQXFlA5mfYZfUg==
  token-validity-in-seconds: 86400
my:
  api-key: ${API_KEY}